- build.gradle
- gradle.properties
- inspectit-oce-core/build.gradle
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/CaseUtils.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/InspectitEnvironment.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/filebased/ConfigurationDirectoriesWatcher.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/InspectitConfig.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/MetricsSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/config/ConfigSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/config/FileBasedConfigSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/exporters/ExportersSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/exporters/metrics/MetricsExportersSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/exporters/metrics/PrometheusExporterSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/exporter/PrometheusExporterService.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/service/ActivationConfigCondition.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/service/ActivationConfigConditionMet.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/service/DynamicallyActivatableService.java
- inspectit-oce-core/src/main/resources/config/default.yml
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/SpringTestBase.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/config/CaseUtilTest.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/exporter/PrometheusExporterIntTest.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/exporter/PrometheusExporterTest.java
- extended the Agent with a base class for services which can be dynamically activated, deactivated and configured through the inspectIT configuration mechanism
- the prometheus OpenCensus exporter was added as a dynamic service (can be enabled, disabled and reconfigured at runtime)
- added config validation via the hibernate implementation
- moved the package rocks.inspectit.oce.config.service to rocks.inspectit.oce.service
> closes #4: Added Prometheus exporter and config validation

- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/InspectitConfig.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/metrics/MetricsSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/tags/TagsSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/tags/providers/EnvironmentTagsProviderSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/tags/providers/TagsProvidersSettings.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/AbstractTagsProvider.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/CommonTagsManager.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/ITagsProvider.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/impl/EnvironmentTagsProvider.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/impl/ExtrasTagsProvider.java
- inspectit-oce-core/src/main/resources/config/default.yml
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/tags/CommonTagsManagerIntTest.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/tags/impl/EnvironmentTagsProviderIntTest.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/tags/impl/ExtrasTagsProviderIntTest.java
- inspectit-oce-documentation/src/docs/asciidoc/_includes/monitoring-environment/common-tags.adoc
- inspectit-oce-documentation/src/docs/asciidoc/_includes/monitoring-environment/index.adoc
- inspectit-oce-documentation/src/docs/asciidoc/index.adoc
Example usages:
* creating view
```
View.create(View.Name.create("some/name"), "some desc", someMeasure, someAggregation, tagsProvider.getCommonTagKeys())
```
* recording metrics view
```
try (Scope scope = tagsProvider.withCommonTagScope()) {
Stats.getStatsRecorder().newMeasureMap().put(someMeasure, 1L).record();
}
```
@JonasKunz let's disucss how should we document this
**Main challendge: How can common tags be included in metrics collected by the user using instrumentation lib?**
As OpenCensus does not provide any mechanism to set common tags, we would need to allow user to access them.. Maybe we can provide some bootstrap interface for this, that user could use to get it, but this way the bootstrap must be a compile depdency for  users as well. We would need to provide NoOp impl as …
> closes #8: support for common tags and tag providers

- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/AgentImpl.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/InspectitEnvironment.java
- inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/SpringConfiguration.java
- inspectit-oce-core/src/main/resources/config/fallback.yml
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/SpringTestBase.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/config/FallbackConfigTest.java
- inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/config/InvalidConfigurationUpdateTest.java
- inspectit-oce-documentation/src/docs/asciidoc/_includes/configuration/configuration-basics.adoc
The configuration loading process has been altered as follows.
Intially, the agent only loads the "inspectit.config" part from the configuration for parsing all configuration sources.
Afterwards, it tries to load the entrie configuration. If this fails, it will use a fallback configuration where everything is disabled. This fallback configuration however will retain the previously loaded "inspectit.config" part, which means that config updates can be passed to the agent.
> closes #18: Added handling of invalid startup configurations

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/callsorting/GenericActionCallSorter.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/callsorting/GenericActionCallSorterTest.java
If two rules used exactly the same ActionCallConfig, this caused the hook builder to fail:
When sorting the actions, normal Hashmaps where used instead of IdentityHashMaps, which caused this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/439)
> Fixed issue for identical action calls

- components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js
Fixes a bug that does not show file content after changing in the tree. Bug reproducible only when switching between editable files (non-defaults)..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/621)
> Follow-up for #570 - Fixed bug in the reducer request counts

- inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
The param "hostname" is needed in docker-compose file, so the inspectIT configsrv could see the different agents in docker environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/648)
> close #647 Add hostname param to docker-compose-prometheus

- inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
The param "hostname" is needed in docker-compose file, so the inspectIT configsrv could see the different agents in docker environment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/649)
> Add hostname param to docker-compose-influxdb

- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/658)
> Closes #642 - Searching for attributes in the web-UI's agent status vew is not working

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/recorder/BeaconRecorder.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorder.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumServerConfiguration.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/ResourceTimingSettings.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java
- components/inspectit-ocelot-eum-server/src/main/resources/application.yml
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorderTest.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManagerTest.java
- inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
Few hits for the review:
* I think without reading a full docs from the Boomerang, it's impossible to review this, especially the parsing of the compressed string for resource timing
* As discussed with @JonasKunz I added a `BeaconRecorder` interfaces that acts on fully processed beacon, extended the manager for this purpose
* Currently I am only counting resources.. However, I would advise that we immediately report the load times instead. We will have the COUNT and SUM views, so we would have both the count on how many, plus the loading times.. Imo there is no reason to start only with counting.. Plus, let's agree on the metric name not sure if `resource_timing_total` is good one. Note that now I could not test the `timing` values, as these are not reported, thus even the tests would be …
> Closes #637 - Exposing count of reported resource timing elements

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorder.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorderTest.java
Don't think there is anything questionable here.. I made the metric type double, as time is a double metric, of course here the rounding by Boomerang are generating ints.. Still I would say this is correct..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/662)
> Closes #660 - Reporting resource response time in the EUM server

- .github/workflows/agent_test.yml
- .github/workflows/configuration_ui_test.yml
- .github/workflows/configurationserver_test.yml
- .github/workflows/eumserver_test.yml
- README.md
- codecov.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/705)
> Display codecov results in pull requests

- inspectit-ocelot-documentation/docs/configuration/plugin-configuration.md
- inspectit-ocelot-documentation/docs/instrumentation/instrumentation.md
- inspectit-ocelot-documentation/docs/instrumentation/rules.md
- inspectit-ocelot-documentation/docs/instrumentation/scopes.md
- inspectit-ocelot-documentation/docs/metrics/common-tags.md
- inspectit-ocelot-documentation/docs/metrics/custom-metrics.md
- inspectit-ocelot-documentation/docs/tracing/log-correlation.md
- inspectit-ocelot-documentation/docs/tracing/privacy.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/709)
> Closes #656 - Use standardized naming schemes in documentation examples

- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/utils/GeolocationResolverIntTest.java
Fixed the `GeolocationResolverIntTest`, I am not sure what the problem was, but it seems that processing the beacon does not mean that the metrics are exposed immediately. Anyway, I think this is way better to test this functionality in the INT test, as old assertions were not really good imo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/731)
> Fixed GeoLocationResolverIntTest of EUM server

- inspectit-ocelot-documentation/docs/instrumentation/rules.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/732)
> Fixed wrong indentation in documentation example

- components/inspectit-ocelot-configurationserver-ui/package.json
- components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/EditSourceComponents/SourceTree.js
- components/inspectit-ocelot-configurationserver-ui/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/764)
> Closes #643 - Updated edit dialog for new primeReact version

- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/_shared/tracing.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/db/jdbc/tracing.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/_shared/http-tracing.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/method-tracing.yml
Closes #746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/747)
> Closes #746 - Added extension point for globally adding trace attributes

- components/inspectit-ocelot-configurationserver/README.md
No code changes needed. I just added an example to README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/697)
> Closes #639 - Logback.xml in the configuration server JAR prevents custom log configurations

- components/inspectit-ocelot-configurationserver/src/main/resources/db/migration/V2__added_user_login_time.sql
The migration will add an empty column for the lastLoginTime. Unfortunately, `null` values are not allowed in this column leading to an exception when a user is loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/789)
> Fixed the configuration server's Flyway migration script version 2

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java
With the endpoint configuration/agent-config in the ConfigurationController agent configurations can now be fetched without the access being logged in the loading history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/784)
> Closes #782 - Added Endpoint for fetching agent configs without logging to agent status.

- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ServletApiContextPropagationTest.java
- inspectit-ocelot-agent/src/system-test/resources/config/global-propagation-test.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/http/httpurlconnection.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/797)
> Fixed occasional duplicate injection of correlation Headers

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TraceIdMDCInjectionSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MDCAccess.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4J1MDCAdapter.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4J2MDCAdapter.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/MDCAdapter.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Slf4jMDCAdapter.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MDCAccessTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/AbstractStaticMapMDCAdapterTest.java
- inspectit-ocelot-documentation/docs/tracing/log-correlation.md
Closes #780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/796)
> Closes #780 - Added opt-out for MDC injection of individual libraries

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/core.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/injection/ClassInjector.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/injection/ClassInjectorTest.java
- inspectit-ocelot-documentation/docs/instrumentation/process.md
Closes #795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/799)
> Closes #795 - Allowed configuration of the ProtectionDomain

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/MetricsAutoCompleter.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/MetricsAutoCompleterTest.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelper.java
- inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelperTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/788)
> Closes #785 - Added autocompleter for declared metric names & fixed bug in ModelAutoCompleter

- gradle.properties
- inspectit-ocelot-core/build.gradle
Closes #821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/822)
> Closes #821 - Added missing Netty SSL dependency for OC-Agent Trace Exporter

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessor.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconTagSettings.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/831)
> Closes #830 - Extend EUM server to handle non existing beacon fields as empty values

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/InspectitServerSettings.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/userdetails/CustomLdapUserDetailsMapper.java
- components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccessIntTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/AutoCommitWorkingDirectoryProxyIntTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
- inspectit-ocelot-documentation/docs/config-server/managing-configurations.md
The mail suffix for internal users can be changed in the config at inspectit-config-server.mail-suffix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/856)
> Closes #845 - Use LDAP-User mails when commiting if available

- components/inspectit-ocelot-configurationserver/build.gradle
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTemplateController.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/TemplateVariable.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskControllerTest.java
- components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/tasks.json
- components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/tasks_conflicting_template.json
Closes #824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/862)
> Closes #824 - Added API for kapacitor tasks

- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/DeleteDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/dialogs/PromotionApprovalDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/DeleteDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ClearDialog.js
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/ConfigurationPromotion.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/PromotionController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/PromotionControllerIntTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/864)
> Closes #803 and #804 - Users may now define custom promotion messages.

- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatus.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManagerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/869)
> Closes #818 and #819 - Branches of which a Mapping originated now displayed in UI.

- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpInMetricTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/883)
> Making HttpInMetricTest more reliable against failure

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/905)
> Closes #894 - Enhance the endpoint to list files with the possibility to specify a version

- components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/SearchDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
- components/inspectit-ocelot-configurationserver-ui/src/hooks/use-fetch-data.js
- components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/913)
> Closes #909 - Extend configuration UI to be able to search in the content of the configuration files

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconRequirement.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/InitiatorType.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconRequirementTest.java
- inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
Closes #923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/924)
> Closes #923 - Added initiator beacon requirement to EUM Server

- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/rules/AlertingRulesView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/AlertingChannelsView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/tree/AlertingChannelsTree.js
closes #920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/925)
> Closes #920 - Kapacitor view starts scrolling when there are too many items in the tree view

- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/939)
> Fix match expression documentation

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvKeyValueExpanderBeaconProcessor.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvKeyValueExpanderBeaconProcessorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/970)
> Closes #966 - Resolve 'rt.bmr' data send by Boomerang plugin RT

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Task.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskControllerTest.java
Closes #980
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/982)
> Closes #980 - Extending the alerting API to reload kapacitor tasks due to changed alerting rules

- inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
- inspectit-ocelot-documentation/docs/instrumentation/rules.md
- inspectit-ocelot-documentation/docs/tracing/log-correlation.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/999)
> Smoothed Average View Documentation

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java
- components/inspectit-ocelot-eum-server/src/main/resources/application.yml
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/JaegerExporterSettings.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1004)
> Closes #1003 - Updated default config.

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java
- components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java
If a value of the rt.bmr beacon is not a number or empty, the log message is printed continuously. 
- Now the Log message is printed only as result of invalid numbers (empty values will be skipped)
- The log message is printed as "trace" log level
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1023)
> Changes behaviour of "invalid value log" in the rt.bmr beacon processor

- inspectit-ocelot-documentation/docs/tracing/log-correlation.md
- inspectit-ocelot-documentation/docs/tracing/tracing.md
closes #1044
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1047)
> Closes #1044 - Adding documentation for the agent's propagation format 

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializer.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializerTest.java
Allow disabling the console log before the log system is initialized
This is required to disable the log on console for:
`
2021-05-30 21:13:44,503 INFO 143 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Starting inspectIT Ocelot Agent...
2021-05-30 21:13:44,504 INFO 144 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Version: SNAPSHOT
2021-05-30 21:13:44,504 INFO 144 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : Build Date: Sun May 30 20:52:21 AEST 2021
2021-05-30 21:13:44,505 INFO 145 --- [inspectIT] [ Thread-0] rocks.inspectit.ocelot.core.AgentImpl : OpenCensus was loaded in inspectIT classloader
2021-05-30 21:13:45,035 INFO 675 --- [inspectIT] [ Thread-0] r.i.o.core.config.InspectitEnvironment : Registered Configuration …
> Allow disabling console log on start-up

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/command/AgentCommandSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/core.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/AgentCommandService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/HttpCommandFetcher.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/AgentCommandServiceTest.java
- inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
- inspectit-ocelot-documentation/docs/configuration/agent-command-configuration.md
- inspectit-ocelot-documentation/website/sidebars.json
closes #1108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1113)
> Closes #1108 - Introduce an option to derive the agent-command url based on the HTTP config URL

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/RemoteConfigurationsSettings.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/ConfigurationPromotion.java
- components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/FileManagerTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManagerTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
closes #1136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1145)
> Closes #1136 - Pull changes of a remote Git repository into the local workspace of a Configuration Server

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManager.java
closes #1180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1190)
> Closes #1180 -  The configuration server does not use custom private keys for authenticating Git fetches

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/hook/WebhookController.java
closes #1178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1194)
>  Closes #1178 - Allow different HTTP methods for the configuration server's synchronization hook endpoint

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/FileInfoVisitorTest.java
Kubernetes uses symlinks within the filesystem to allow updates of Config Maps during runtime.
This fix skips hidden folders with configuration files and symbolic links are followed and read from
in case that a file is referenced by the symbolic link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1206)
> Closes #1205 - Reading configuration from mapped Kubernetes Config Maps

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1312)
> Introduce issue templates

- THIRD-PARTY-LICENSES.txt
- components/inspectit-ocelot-configdocsgenerator/build.gradle
- components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/ConfigDocsGenerator.java
- components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParser.java
- components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/parsing/ConfigParserTest.java
- components/inspectit-ocelot-configurationserver/build.gradle
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/ConfigurationControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1314)
> Closes #1290 - Add an endpoint to the Configuration Server to obtain a configuration documentation

- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/BeanConfiguration.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporter.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java
- components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1346)
> fix(EUM-server): Add conversion-service to EUM server

- components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/yamlhighlighter/HighlightRulesMapController.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1355)
> Closes #1354 - fix(config-server/config-server-ui) Support enums in Collections in Highlighting

- components/inspectit-ocelot-configdocsgenerator/build.gradle
- components/inspectit-ocelot-configurationserver/build.gradle
- components/inspectit-ocelot-eum-server/build.gradle
- gradle.properties
- inspectit-ocelot-agent/build.gradle
- inspectit-ocelot-bootstrap/build.gradle
- inspectit-ocelot-config/build.gradle
- inspectit-ocelot-core/build.gradle
- inspectit-ocelot-sdk/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1364)
> feat: upgrade lombok to the latest version

- .circleci/config.yml
- build.gradle
- components/inspectit-ocelot-configurationserver/build.gradle
- components/inspectit-ocelot-eum-server/build.gradle
- gradle.properties
- inspectit-ocelot-core/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1367)
> feat: generate SBOM file for releases

- inspectit-ocelot-documentation/website/siteConfig.js
Closes #1389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1390)
> Fix editUrl of the Ocelot end-user documentation

- components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js
Closes #1383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1391)
> Closes #1383 - Method configuration editor: preserve Trace and Measure settings when editing existing scope

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1392)
> Fixing the docker build step in the CI release workflow

- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/scopes/db/jdbc.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1414)
> Fix default config for JDBC scopes

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1417)
> Update contribute.md file for latest IntelliJ Versions

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloader.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/LogPreloaderTest.java
Artificially added log events will look like follows.
`2022-04-29 10:47:42,709 INFO  33860  --- [inspectIT] [pectit-thread-1] ### LOG-INVALIDATING EVENT ###           : Property sources reload! Some previous log messages may now be outdated.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1411)
> Closes #1407 - Insert events into preloaded logs

- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
- inspectit-ocelot-documentation/docs/metrics/metric-exporters.md
- inspectit-ocelot-documentation/docs/tracing/trace-exporters.md
- inspectit-ocelot-documentation/website/versioned_docs/version-2.0.0/metrics/metric-exporters.md
- inspectit-ocelot-documentation/website/versioned_docs/version-2.0.0/tracing/trace-exporters.md
Closes #1434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1435)
> Closes #1434: Fix Divergence of Documentation for Default Config and Default Config itself

- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
closes #1286 
Added a new column in the agent table with indicators of the active services' state
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1455)
> feat: Config UI shows warning and error status of agents

- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/db/jdbc.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/db/jdbc/metrics.yml
The provided changes collect the metric jdbc/query/duration with views sum and count. The labels are the requested database (`jdbc_url`), the command like SELECT, UPDATE, ... (`sql_command`) and the called JDBC method (`jdbc_operation`).
The metric is a missing counterpart to the JDBC span collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1420)
> Export metric about duration of JDBC queries

- inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/EnvironmentInformationPropertySource.java
Removed Logger intialization from AgentMain.java
Made EnvironmentInformationPropertySource#getAgentJarDirectory Wildfly save
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1467)
> Closes #1465 - Since 2.0.0 Wildfy Server refuses to start

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/yamlhighlighter/HighlightRulesMapController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/yamlhighlighter/HighlightRulesMapControllerIntTest.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
Closes #1436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1488)
> Highlight enums with String values correctly

- CONTRIBUTING.md
- codequality/idea/code_style.xml
- components/inspectit-ocelot-configurationserver-ui/.eslintrc
- components/inspectit-ocelot-configurationserver-ui/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1496)
> Add settings and info for developing UI in IntelliJ

- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OtlpMetricsExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/resources/otel-config.yaml
Closes #1512 
Upgrade the image used for the OpenTelemetry Collector (contrib) in the exporter integration tests.
* upgrade the otelcol-contrib image
* set compression to `none` in the otlp exporter defined in otel-colfig.yaml (from v0.44.0 to v0.45.0, the default compression of the otlp exporter of the OpenTelemetry Collector was changed to `gzip`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1514)
> Closes #1512: [Feature] - Update otel-collector image used in integration tests to latest

- components/inspectit-ocelot-configurationserver-ui/README.md
Updated the Readme from in the config server ui component to help developers who code in VS code to deal with prettier errors in the Config Server UI tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1529)
> Feature: Update Readme to help developers handle prettier errors.

- inspectit-ocelot-config/build.gradle
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/CompressionMethod.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/OtlpTraceExporterSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
- inspectit-ocelot-core/build.gradle
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpMetricsExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OtlpMetricsExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImplIntTest.java
- inspectit-ocelot-documentation/docs/metrics/metric-exporters.md
- inspectit-ocelot-documentation/docs/tracing/trace-exporters.md
Closes #1534 and #1536
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1536)
> Closes #1534 and #1536 - Otlp*ExporterService does not expose underlying OTEL  configuration

- THIRD-PARTY-LICENSES.txt
- gradle.properties
- inspectit-ocelot-config/build.gradle
- inspectit-ocelot-core/build.gradle
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/DynamicallyActivatableMetricsExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/LoggingMetricExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpMetricsExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/PrometheusExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/DynamicMultiSpanExporter.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/LoggingMetricsExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImplTest.java
Upgrade OpenTelemetry to [v1.17.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.17.0)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1515)
> Upgrade OpenTelemetry to v1.17.0

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/AutoTracingSettings.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java
Closes #1565
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1566)
> Closes #1565: [Bug] - No default sample-mode for auto tracing settings

- components/inspectit-ocelot-configdocsgenerator/build.gradle
The configdocsgenerator was missing OpenTelemetry dependencies, see https://github.com/inspectIT/inspectit-ocelot/actions/runs/3997231832/jobs/6858288326
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1567)
> Add missing dependency to configdocsgenerator

- inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
- inspectit-ocelot-documentation/docs/metrics/metric-exporters.md
As part of https://github.com/inspectIT/inspectit-ocelot-eum-server/issues/12, this PR updates the documentation of the tracing and metrics exporter of the EUM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1569)
> Update EUM-Server exporter documentation

- .circleci/config.yml
This PR increase the timeout for generating GitHub Pages in CircleCi and moves this action into a separate step, so that a failure in this step does not block the entire workflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1570)
> Increase time out for generating GitHub Pages in CircleCi

- inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
A previous commit only documented how to secure requests regarding beacons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1573)
> Documents how to secure requests regarding spans.

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/OtlpMetricsExporterSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/JaegerExporterSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/OtlpTraceExporterSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/ZipkinExporterSettings.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/utils/EndpointUtils.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpMetricsExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OtlpTraceExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/VariableAccessorFactory.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/IObfuscatory.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/SpanAttributeObfuscationExportIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/service/DynamicallyActivatableServiceObserverIntTest.java
Closes #1574
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1575)
> Closes #1574: [Bug] - Span attributes not added when obfuscator is enabled

- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js
Closes #1582: Fixed the unwanted behavior when aborting the log preloading dialog, by implementing the AbortController.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1583)
> Closes #1582 Fix unwanted behavior when aborting the log preloading dialog

- .github/workflows/configuration_ui_test.yml
- components/inspectit-ocelot-configurationserver/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1585)
> Export step during frontend build is successful

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerDeadlockGh1597IntTest.java
There could have been a deadlock if AgentHealthManager is invalidated while a change in Health is happening from different threads. Details see https://github.com/inspectIT/inspectit-ocelot/issues/1597
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1599)
> Closes #1597: [Bug] - CRITICAL: Deadlock AgentHealthManager and failing instrumentation

- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/AlertingView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/rules/tree/AlertingRulesTree.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js
#1547
#1600
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1601)
> Alerting Tab and minor bug fixes

- inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java
- inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/IAgent.java
- inspectit-ocelot-documentation/docs/instrumentation/process.md
This property is rarely useful. There are cases you want to start an application with inspectit's agent attached but inspectit should pick up its work only after a configurable amount of milliseconds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1606)
> Delays start of inspectit for a configurable amount of time

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/AgentCommandSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
The timeout is set to the same value as on the server side, so there is no time left to receive the no content response.
Solution: add another 10s on the agent side to be able to receive the response.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1618)
> fix agent error status by increasing the agent command timeout

- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/BrowserPropagationHttpExporterService.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/BrowserPropagationServlet.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/browser/BrowserPropagationDataStorage.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/browser/BrowserPropagationSessionStorage.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/BrowserPropagationUtil.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/BrowserPropagationHttpExporterServiceIntTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/browser/BrowserPropagationDataStorageTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/BrowserPropagationUtilTest.java
- inspectit-ocelot-documentation/docs/tags/tags-exporters.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1620)
> update default session-id-header for tags-http-exporter

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/browser/BrowserPropagationDataStorageTest.java
- inspectit-ocelot-documentation/docs/instrumentation/rules.md
- inspectit-ocelot-documentation/docs/tags/tags-exporters.md
If a BrowserPropagationDataStorage is not created in the first context, but in a later one, earlier created data, which was down propagated still has to be included into the data storage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1621)
> add down propagated data to late BrowserPropagationDataStorage

- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/FrontendConfiguration.java
- components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1635)
> patch server-UI and TagValueGuard

- inspectit-ocelot-documentation/docs/getting-started/docker-examples.md
1. Change docker-compose to docker compose due discontinuity of support and native integration available on docker
2. Add helper for users under corporate VPN for internet connectivity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1637)
> change docker-compose to docker compose

- inspectit-ocelot-documentation/docs/config-server/overview.md
- inspectit-ocelot-documentation/docs/tracing/tracing.md
- typo fix for inspectit-ocelot-documentation/docs/tracing/tracing.md
- link fix for inspectit-ocelot-documentation/docs/config-server/overview.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1638)
> minor typo and link fixes

- components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js
- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/AgentHealthStateDialogue.js
- components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/initial-states.js
- components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/mappings/reducers.js
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingManager.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializer.java
- components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/promotion/PromotionController.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingManagerTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializerTest.java
- components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/promotion/PromotionControllerIntTest.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidator.java
Add progress spinner for AgentMapping-UI and cache agent mappings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1639)
> improve agent mappings page

- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuard.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/tagGuards/PersistedTagsReaderWriter.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/MeasureTagValueGuardTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/tagGuards/PersistedTagsReaderWriterTest.java
Check, if the directory for the tag-guard-database is writable
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1656)
> Check tagguard directory

- components/inspectit-ocelot-configurationserver/build.gradle
Seems like default output has changed to application.cdx.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1660)
> fix: pipeline wants to copy bom.json.

- components/inspectit-ocelot-configurationserver-ui/package.json
- components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
- components/inspectit-ocelot-configurationserver-ui/yarn.lock
- inspectit-ocelot-documentation/website/yarn.lock
The status page might render too early, resulting in a null error. This PR adds a null check for this situation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1669)
> fix ui-bug

- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tags/providers/EnvironmentTagsProviderSettings.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/core.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/impl/EnvironmentTagsProvider.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/impl/EnvironmentTagsProviderIntTest.java
- inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
- inspectit-ocelot-documentation/docs/metrics/common-tags.md
Let's keep the property `inspectit.tags.providers.environment.resolve-host-address`.
As tag key we will use `host.ip` instead of `host_address`.
> Revert provider property name change

- THIRD-PARTY-LICENSES.txt
- components/inspectit-ocelot-configschemagenerator/build.gradle
- gradle/configserverlibs.versions.toml
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/UserInstrumentationWithMetricsTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/HttpServiceOutMetricTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/JdbcServiceOutMetricTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceSettingsTest.java
- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/debug.yml
- inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/_shared/service-graph.yml
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/impl/EnvironmentTagsProvider.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/impl/EnvironmentTagsProviderIntTest.java
- inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
- inspectit-ocelot-documentation/docs/instrumentation/data-propagation.md
- inspectit-ocelot-documentation/docs/metrics/common-tags.md
As announced in the previous release, the `service` tag will be replaced by the `service.name` tag in metrics
> Remove deprecated service tag

- .github/workflows/agent_security_check.yml
- .github/workflows/configurationserver_security_check.yml
Replace Slack notifications with Email. Since GitHub cannot send emails directy, we use [Resend](https://resend.com).
> Update GitHub notifications

- components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
Spring Boot supports virtual threads for Java 21 since version 3.2, which are recommend for server applications that handle a lot of requests. In our case handling a lot of agents requesting their configuration.
> Enable virtual threads for configuration server

- inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceSettingsTest.java
- inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/privacy/obfuscation/ObfuscationPattern.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManager.java
- inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/PatternObfuscatory.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java
- inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/PatternObfuscatoryTest.java
- inspectit-ocelot-documentation/docs/tracing/privacy.md
Closes #576
Replace-Regex patterns will be compiled for every configuration change. During attribute writing the patterns should be ready to use.
> Closes #576 - Use replace-regex when obfuscating data
