inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/SpringConfiguration.java

```
2018-12-28 15:33:33,337 INFO  64719  --- [inspectIT] [pectit-thread-0] .o.c.c.f.ConfigurationDirectoriesWatcher : reloading /home/ise/workspace/mbconnect/mme-hu-shop-controller/src/main/resources
2018-12-28 15:33:33,875 INFO  65257  --- [inspectIT] [pectit-thread-1] .o.c.c.f.ConfigurationDirectoriesWatcher : reloading /home/ise/workspace/mbconnect/mme-hu-shop-controller/src/main/resources
```

name the threads we create accordingly

---

inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ClassLoaderMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/DiskMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/GCMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/MemoryMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ProcessorMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/ThreadMetricsSysTest.java
inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/metrics/selfmonitoring/SelfMonitoringSysTest.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/OpenCensusConfiguration.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/metrics/GCMetricsSettings.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/metrics/MetricsSettings.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/metrics/StandardMetricsSettings.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/config/model/metrics/StandardPollingMetricsRecorderSettings.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/AbstractMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/AbstractPollingMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/ClassLoaderMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/DiskMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/GCMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/MemoryMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/ProcessorMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/ThreadMetricsRecorder.java
inspectit-oce-core/src/main/resources/config/default.yml

For now I have focused on system tests. I havent't spent time on writing integration tests for testing configuration changes. Should we do this?

work on #7: Added recorders for gc, threads and memory

---

.travis.yml
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/GCMetricsRecorder.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/metrics/ProcessorMetricsRecorder.java

See the following build as a sample for this configuration: https://travis-ci.com/mariusoe/inspectit-oce/builds/96524934

Improved CI configuration - Testing on multiple JDKs in parallel and deploying documentation to S3

---

inspectit-oce-documentation/src/docs/asciidoc/_includes/getting-started/docker-compose-example.adoc

Starting the Demo on Windows using WSL

---

README.md
inspectit-oce-agent/README.md
inspectit-oce-bootstrap/README.md
inspectit-oce-core/README.md
inspectit-oce-demo/README.md
inspectit-oce-documentation/README.md
inspectit-oce-documentation/src/docs/asciidoc/_includes/metrics/metrics-recorders.adoc

You can use my repository in order to see it rendered: https://github.com/mariusoe/inspectit-oce/tree/36-adding-readme

closes #36 - adding readme files

---

inspectit-oce-bootstrap/src/main/java/rocks/inspectit/oce/bootstrap/instrumentation/ClassLoaderDelegationMarker.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/instrumentation/special/ClassLoaderDelegation.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-oce/140)

Ensured that classloader delegation is only performed once to prevent stack overflows

---

inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/instrumentation/special/ClassLoaderDelegation.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-oce/143)

Second attempt on fixing the IBM bootstrap classloader instrumentation.

---

inspectit-oce-agent/src/system-test/java/rocks/inspectit/oce/instrumentation/UserInstrumentationWithMetricsTest.java
inspectit-oce-core/src/main/java/rocks/inspectit/oce/core/tags/impl/EnvironmentTagsProvider.java
inspectit-oce-core/src/test/java/rocks/inspectit/oce/core/tags/impl/EnvironmentTagsProviderIntTest.java
inspectit-oce-demo/grafana/provisioning/influxdb/dashboards/jvm-metrics.json
inspectit-oce-demo/grafana/provisioning/influxdb/dashboards/self-monitoring.json
inspectit-oce-demo/grafana/provisioning/influxdb/dashboards/system-metrics.json
inspectit-oce-demo/grafana/provisioning/prometheus/dashboards/jvm-metrics.json
inspectit-oce-demo/grafana/provisioning/prometheus/dashboards/self-monitoring.json
inspectit-oce-demo/grafana/provisioning/prometheus/dashboards/system-metrics.json

I tested both demo versions :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-oce/145)

Closes #144 - unified common tag names

---

README.md
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/ClassLoaderMetricsSysTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/DiskMetricsSysTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/MemoryMetricsSysTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/ProcessorMetricsSysTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/ThreadMetricsSysTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/selfmonitoring/SelfMonitoringSysTest.java
inspectit-ocelot-agent/src/system-test/resources/config/agent-overwrites.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/model/InspectitConfig.java
inspectit-ocelot-core/src/main/resources/config/default.yml
inspectit-ocelot-documentation/src/docs/asciidoc/_includes/configuration/open-census-configuration.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-oce/147)

Closes #146 - Made start asynchronous when run via javaagent.

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/ExecutorContextPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/ScheduledExecutorContextPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/ThreadStartContextPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/remote/ApacheHttpClientContextPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/remote/HttpUrlConnectionContextPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/remote/ServletApiContextDownPropagationSensor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/special/remote/ServletApiContextUpPropagationSensor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/155)

Closes #150 - fixed circular dependency from ContextManager

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/metrics/MetricsSysTestBase.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/AgentManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/157)

Providing initialization flag via AgentManager

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/ClassLoaderDelegationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/InstrumentationScopesTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/InstrumentationSysTestBase.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ApacheHttpClientContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ServletApiContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/159)

Extended test utility for ability to wait for class instrumentations

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/165)

Updated Docker build and test images

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/ClassLoaderDelegationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ThreadStartContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ServletApiContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/filebased/ConfigDirWatchingIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/179)

Fixed system and integration tests

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ThreadStartContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ApacheHttpClientContextPropagationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/180)

Fixed system tests attempt two

---

inspectit-ocelot-documentation/src/docs/asciidoc/_includes/getting-started/docker-compose-example.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/184)

Fixed broken dashboard links in documentation.

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/181)

Ensured that tests wait five seconds for instrumentations to become active

---

inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/model/exporters/metrics/MetricsExportersSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/model/exporters/metrics/OpenCensusAgentMetricsExporterSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/model/exporters/trace/OpenCensusAgentTraceExporterSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/model/exporters/trace/TraceExportersSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterService.java
inspectit-ocelot-core/src/main/resources/rocks/inspectit/ocelot/core/config/default/exporters.yml
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentMetricsExporterServiceIntTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/OpenCensusAgentTraceExporterServiceIntTest.java
inspectit-ocelot-documentation/src/docs/asciidoc/_includes/metrics/metrics-exporters.adoc
inspectit-ocelot-documentation/src/docs/asciidoc/_includes/tracing/tracing-exporters.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/182)

Closes #169: Added additional exporters

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
inspectit-ocelot-agent/src/system-test/resources/config/TraceSettingsTest.yml
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/RuleTracingSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/MethodTracingConfiguration.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/StartSpanAction.java
inspectit-ocelot-documentation/src/docs/asciidoc/_includes/instrumentation/rules.adoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/188)

Changed default span name, altered tracing conditions

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/data/DataSettings.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/202)

Fixed wrong configuration binding for is-tag property due to invalid setter name

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/206)

Changed OCE logo to Ocelot in readme

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/ConfigSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/FileBasedConfigSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/HttpConfigSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/file/ConfigurationDirectoriesPoller.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/file/ConfigurationDirectoriesWatcher.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/file/DirectoryPropertySource.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPoller.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/util/PropertyUtils.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/service/DynamicallyActivatableService.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/file/ConfigDirWatchingIntTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPollerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/util/PropertyUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/218)

Closes #199 - Fetching configuration via HTTP

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/commons/httpurlconnection.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/http/http-httpurlconnection.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-commons.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-httpurlconnection.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-jdbc.yml
inspectit-ocelot-demo/agentconfig/api-gateway/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/api-gateway/sql.yml
inspectit-ocelot-demo/agentconfig/api-gateway/tracing.yml
inspectit-ocelot-demo/agentconfig/config-server/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/config-server/sql.yml
inspectit-ocelot-demo/agentconfig/config-server/tracing.yml
inspectit-ocelot-demo/agentconfig/customers-service/config.yml
inspectit-ocelot-demo/agentconfig/customers-service/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/customers-service/sql.yml
inspectit-ocelot-demo/agentconfig/customers-service/tracing.yml
inspectit-ocelot-demo/agentconfig/discovery-server/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/discovery-server/sql.yml
inspectit-ocelot-demo/agentconfig/discovery-server/tracing.yml
inspectit-ocelot-demo/agentconfig/vets-service/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/vets-service/sql.yml
inspectit-ocelot-demo/agentconfig/vets-service/tracing.yml
inspectit-ocelot-demo/agentconfig/visits-service/parametrize-http-paths.yml
inspectit-ocelot-demo/agentconfig/visits-service/sql.yml
inspectit-ocelot-demo/agentconfig/visits-service/tracing.yml
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/service-graph.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/227)

Closes #64 - Added service graph and http metrics for HttpURLConnection

---

components/inspectit-ocelot-eum-server/README.md
components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/EUMServerApplication.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/PrometheusExporterService.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/model/config/BeaconMetricDefinition.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/model/config/Configuration.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/model/config/EUMTagsSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/service/BeaconController.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/PrometheusExporterServiceIntTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManagerTest.java
settings.gradle

…in repository
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/229)

Closes #228 - Move inspectit-ocelot-eum server to main repo

---

gradle.properties

Love inspectit, but also the newest versions of grpc and opencensus. Not sure if this ok. This is my very first open source PR. 🥂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/230)

Bump Opencensus Version to 0.22.1

---

inspectit-ocelot-documentation/website/siteConfig.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/232)

Added Algolia search for documentation

---

inspectit-ocelot-agent/build.gradle
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/HttpServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/JdbcServiceOutMetricTest.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/commons/jdbc.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/237)

Closes #235, #236 - Fixed bugs in JDBC instrumentation

---

.circleci/config.yml
build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/243)

Fix generation of JaCoCo code coverage reports

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/244)

Use temp directories in logging unit tests

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/actions/template/GenericActionTemplate.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/actions/template/VoidGenericActionTemplate.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/actions/GenericActionGeneratorIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/240)

Closes #183 - Added cache to actions

---

inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/grafana/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/242)

Integrated service graph panel into to grafana docker image

---

inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/load/Dockerfile
inspectit-ocelot-demo/load/docker-entrypoint.sh
inspectit-ocelot-demo/load/load-script.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/241)

Avoided memory leak in load script of the demo, fixed usage behaviour

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/254)

Upload test-results of component projects to CircleCI

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/HttpConfigSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/249)

Closes #248 - Added attributes to HTTP config fetching

---

inspectit-ocelot-documentation/docs/getting-started/docker-examples.md

Hey guys!! Here there is a little type that I have been found and fixed. Be free to merge to original master when you decide.
Thank you for your help!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/258)

Typo in a demo number 2

---

inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/256)

Closes #234: Add EUM server documentation to Docusaurus

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/http/http-servletapi.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/260)

Fixed bug in servlet-api default config

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/301)

Upgraded package dependencies of configuration UI

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/303)

Fixed leaking file handled when listing files in a directory

---

components/inspectit-ocelot-configurationserver/build.gradle
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/authentication/JwtTokenFilter.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SecurityConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/ErrorInfo.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/users/AccountController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/users/UserController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/config/SecurityConfigurationIntTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/users/AccountControllerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/300)

Closes #286 - Added REST API to change the password

---

THIRD-PARTY-LICENSES.txt
components/inspectit-ocelot-configurationserver/build.gradle
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationReloadTask.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/BeanConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/InspectitServerSettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileChangedEvent.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingsChangedEvent.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java
components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationReloadTaskTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/FileManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/agent/AgentControllerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/293)

Closes #264, #265 - Added preloading and caching to configuration fetching

---

.gitignore
components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/src/components/editor/AceEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/data/yaml-editor-config.json
components/inspectit-ocelot-configurationserver-ui/src/layout/MainLayout.js
components/inspectit-ocelot-configurationserver-ui/src/pages/configuration.js
components/inspectit-ocelot-configurationserver-ui/yarn.lock

This PR is based on PR #302 thus blocked until that PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/304)

Closes #279 - Implement configuration file view component

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/DeleteDialog.js
components/inspectit-ocelot-configurationserver-ui/src/lib/axios-api.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/index.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/queries.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/selectors.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/types.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/utils.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/initial-states.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileData.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/306)

Closes #280 - Added dialogs to create and delete directories and files

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/AceEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/DeleteDialog.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/310)

Refactoring of EditorView component

---

components/inspectit-ocelot-configurationserver-ui/next.config.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/authentication/NoPopupBasicAuthenticationEntryPoint.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/SecurityConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/filters/UiForwardFilter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/318)

Closes #313 - Fix UI packaging within the boot Jar

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/AceEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/types.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/utils.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/initial-states.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/317)

Closes #281 - Implement the logic for managing the configuration files

---

components/inspectit-ocelot-configurationserver/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/322)

Adds task for installing front end dependencies before building it

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/327)

Show a notification when a configuration file has been saved

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/328)

Prevent overwriting selected file content when creating new files

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingManager.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingManagerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/326)

Closes #325 - Adding default agent mapping if none exists

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/ConfigurationServer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/324)

Closes #323 - Ensured working directory is created before spring context is initialized

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/dialogs/ClearDialog.js
components/inspectit-ocelot-configurationserver-ui/src/data/side-navigation-items.json
components/inspectit-ocelot-configurationserver-ui/src/pages/status.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/agent-status/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/agent-status/index.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/agent-status/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/agent-status/types.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/index.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/initial-states.js
components/inspectit-ocelot-configurationserver-ui/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/319)

Closes #308 - Added Agent Status UI

---

.circleci/config.yml
components/inspectit-ocelot-configurationserver-ui/src/components/example/Examples.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/338)

Closes #337 - Add Ocelot Configuration Server Jar as file to the release artifacts

---

inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/http-overview-influxql.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/jvm-metrics.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/self-monitoring.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/service-graph-influxql.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/system-metrics.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/http-overview.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/jvm-metrics.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/self-monitoring.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/service-graph.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/system-metrics.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/347)

Lowered refresh rate of dashboards of the demo scenarios

---

.circleci/config.yml
components/inspectit-ocelot-eum-server/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/357)

Add Ocelot EUM Server Jar as file to the release artifacts

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/AuthenticationRouter.js
components/inspectit-ocelot-configurationserver-ui/src/data/constants.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/authentication/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/authentication/index.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/authentication/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/authentication/types.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/345)

Closes #276: Renew authetication token when expired

---

inspectit-ocelot-documentation/docs/config-server/configuration.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/363)

Adding SSL documentation

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumTagsSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconPreProcessor.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/IPUtils.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/configuration/model/EumTagsSettingsTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/BeaconPreProcessorTest.java
inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/355)

Option to define custom IP address ranges in the EUM server

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/376)

Closes #375 - Add Commit Message Validation to Build Pipeline

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/AutoCompleteRequest.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/AutoCompleter.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleter.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/autocomplete/AutocompleteController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/utils/CaseUtils.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelper.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/utils/CaseUtilTest.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelperTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidator.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/397)

Autocomplete api

---

components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/InspectitConfig.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidator.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidatorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/409)

Added EventListener and fixes in PropertyNamesValidator

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleter.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelper.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/411)

Closes #410 - Checking paths now via Write-Method & Filtering properties where Write-Method is null

---

.circleci/config.yml
inspectit-ocelot-demo/grafana/marketplace/dashboard-mapping.txt
inspectit-ocelot-demo/grafana/marketplace/influx/http.json
inspectit-ocelot-demo/grafana/marketplace/influx/jvm.json
inspectit-ocelot-demo/grafana/marketplace/influx/selfmonitoring.json
inspectit-ocelot-demo/grafana/marketplace/influx/servicegraph.json
inspectit-ocelot-demo/grafana/marketplace/influx/system.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/http.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/jvm.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/selfmonitoring.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/servicegraph.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/system.json
resources/upload-all-dashboards.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/400)

Added task to release Dashboards to Grafana Marketplace automatically

---

CONTRIBUTING.md
README.md

- Good PR to start contributing, I guess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/423)

Fixed link to CONTRIBUTING.md

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumServerConfiguration.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/431)

Closes #429 - Change root property name of EUM server

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/PrometheusExporterServiceIntTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/GeolocationResolverIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/435)

Closes #340 - Migrate unit tests of the EUM server project to JUnit 5

---

components/inspectit-ocelot-eum-server/build.gradle
gradle.properties
inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/432)

Closes #430 - Extend EUM server to provide Boomerang agent files

---

inspectit-ocelot-demo/grafana/marketplace/influx/selfmonitoring.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/selfmonitoring.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/self-monitoring.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/self-monitoring.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/436)

Added log metrics to dashboards

---

components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleterTest.java
inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java
inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/Instances.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/InspectitConfig.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/HttpConfigSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/env/EnvironmentSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/EnvironmentInformationPropertySource.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPoller.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPollerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java
inspectit-ocelot-documentation/docs/configuration/external-configuration-sources.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/438)

Closes #405 - Added persistence file to http config fetching

---

inspectit-ocelot-agent/build.gradle
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/correlation/log/LogCorrelationTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MDCAccess.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4J2MDCAdapter.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/MDCAdapter.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Slf4jMDCAdapter.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MDCAccessTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4j2MDCAdapterTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Slf4jMDCAdapterTest.java
inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/437)

Closes #389 - Added Log4J2 log-trace correlation

---

inspectit-ocelot-documentation/docs/tracing/log-correlation.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/447)

Closes #398 - Added documentation for trace and log correlation

---

THIRD-PARTY-LICENSES.txt
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/ModelAutoCompleterTest.java
inspectit-ocelot-config/build.gradle
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/InspectitConfig.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/plugins/PluginSettings.java
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/PropertyNamesValidator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/PropertySourcesChangedEvent.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/plugins/LoadedPlugin.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/plugins/PluginLoader.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolverTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/plugins/LoadedPluginTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/plugins/PluginLoaderTest.java
inspectit-ocelot-core/src/test/resources/rocks/inspectit/ocelot/core/plugins/my-default.yml
inspectit-ocelot-documentation/docs/configuration/plugin-configuration.md
inspectit-ocelot-documentation/website/sidebars.json
inspectit-ocelot-sdk/build.gradle
inspectit-ocelot-sdk/src/main/java/rocks/inspectit/ocelot/sdk/ConfigurablePlugin.java
inspectit-ocelot-sdk/src/main/java/rocks/inspectit/ocelot/sdk/OcelotPlugin.java
settings.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/259)

Closes #193 - Added plugin system

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/ConfigurationServer.java
components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/452)

Fixed invalid root configuration properties

---

inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/docker-compose-wavefront-zipkin.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/462)

Closes #460 - Fix environment variables in the demo docker-compose files

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtil.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtilTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/463)

Closes #395 - Print bad propagation headers in case they cannot be parsed

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/469)

Closes #369 - Add checksum of release artifacts to releases

---

components/inspectit-ocelot-configurationserver-ui/next.config.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/LoginView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/471)

Closes #467 - Show version number at login screen of configuration server

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tags/TagsSettings.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/484)

Closes #483 - Fixed invalid tag property message

---

.circleci/config.yml

Made attach-alpine-jdk8 independent from third party Jar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/495)

Fixed attach-alpine-jdk8 CircleCI Test

---

inspectit-ocelot-documentation/docs/config-server/agent-mappings.md
inspectit-ocelot-documentation/docs/configuration/open-census-configuration.md
inspectit-ocelot-documentation/docs/configuration/plugin-configuration.md
inspectit-ocelot-documentation/docs/instrumentation/rules.md
inspectit-ocelot-documentation/docs/instrumentation/scopes.md
inspectit-ocelot-documentation/docs/metrics/custom-metrics.md
inspectit-ocelot-documentation/docs/metrics/metric-exporters.md
inspectit-ocelot-documentation/docs/metrics/metric-recorders.md
inspectit-ocelot-documentation/docs/metrics/metrics.md
inspectit-ocelot-documentation/docs/tracing/trace-exporters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/497)

Closes #496 - Spell fixing within documentation

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/498)

Closes #370 - Change misleading label in the configuration file view of the configuration UI

---

inspectit-ocelot-documentation/docs/breaking-changes/0.4.md
inspectit-ocelot-documentation/docs/breaking-changes/0.5.md
inspectit-ocelot-documentation/docs/breaking-changes/0.6.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/499)

Closes #470 - Added breaking changes section to documentation

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/commons/httpurlconnection.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/494)

Closes #493 - Fixed HttpUrlConnection status fetching

---

.gitignore
inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/docker-compose-wavefront-zipkin.yml

Updates to Docker-compose files, to remove warnings from yamllint.
See https://github.com/adrienverge/yamllint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/503)

Fix lint problems of the demos' Dockerfiles

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/504)

HttpPropertySourceState skipps persistence file writing if first attempt fails

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/userlist/UserListView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/userlist/UserToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/lib/axios-api.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/types.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/520)

Closes #519 - Add ability to create user via config UI

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/DeleteDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/userlist/UserDataTable.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/settings/types.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/529)

Closes #528 - Delete User via UI

---

components/inspectit-ocelot-configurationserver/src/main/resources/logback.xml
inspectit-ocelot-documentation/docs/config-server/log-config.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/522)

Closes #517 - Create separate files for config server logs

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/DownloadDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/EditDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/EditSourceComponents/SourceToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/KeyValueEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/settings/userlist/UserDataTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/541)

Fixed some style warnings within settings and mapping view

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/AceEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/utils.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/544)

Closes #378 - Display the default configuration in the config server UI

---

inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/docker-compose-wavefront-zipkin.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/558)

Fixed OOM errors in demo after switching from alpine to ubuntu for config server

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/569)

Closes #568 - EUM Server stops beacon processing after first recorded metric

---

inspectit-ocelot-agent/src/system-test/resources/config/AnnotationAccessTest.yml
inspectit-ocelot-agent/src/system-test/resources/config/EntryPointDetectionTest.yml
inspectit-ocelot-agent/src/system-test/resources/config/ObjectAttachmentsTest.yml
inspectit-ocelot-agent/src/system-test/resources/config/UserInstrumentationWithMetricsTest.yml
inspectit-ocelot-config/build.gradle
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/NumberToMetricRecordingSettingsConverter.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToMetricRecordingSettingsConverter.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/MetricRecordingSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/http/http-apacheclient.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/http/http-httpurlconnection.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/http/http-servletapi.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/method-duration-sensor.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-apacheclient.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-httpurlconnection.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-jdbc.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/service-graph/servicegraph-servletapi.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/model/MetricAccessor.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationRuleResolverTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImplTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorderTest.java
inspectit-ocelot-documentation/docs/breaking-changes/1.1.md
inspectit-ocelot-documentation/docs/instrumentation/rules.md

Quick review intro..
What's missing:
* documentation -> what are all the places that should be changed now?
What's up for discussion:
- There are one or two `TODO`s left, lets quickly agree on this
- Do we wanna forbid same keys in constant and data tags? Currently data would overwrite constant if available
What should be checked:
- As in the other PR, I changed the Gradle build pick of the `JAVA_HOME` as it was not working when started from Intellij. Please check if system tests work from console + IDE for you
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/572)

Closes #563 - Metric tags to be explicit on metric recording

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationReloadTask.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationReloadTaskTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/582)

Closes #581 - Configuration server fails when processing configuration files if a file exists containing invalid characters

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceSettingsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceTestBase.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/585)

Closes #500 - TraceTestBase is unstable and occasionally failing

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/rest/BeaconController.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/rest/BeaconControllerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/584)

Closing #583 - Accepting EUM beacons using GET requests

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CsvExpanderBeaconProcessorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/591)

Closes #590 - Resolve additonal EUM data send by Boomerang in `t_other`

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/BeanConfiguration.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/593)

Closes #553 - Added Influx Exporter to EUM Server

---

inspectit-ocelot-documentation/docs/breaking-changes/1.1.md
inspectit-ocelot-documentation/website/versioned_docs/version-1.1/breaking-changes/1.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/598)

Fixed broken link in breaking changes documentation

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/SelfMonitoringDelegatingObfuscatory.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/privacy/obfuscation/ObfuscationManagerTest.java

I guess this is all what's needed.. 
* I concluded no doc updates are needed
* I concluded no config updates are needed
* I concluded no dashboard updates are needed
Let me know if I am wrong..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/608)

Closes #575 - Added self-monitoring for the obfuscation

---

inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/AgentManager.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/env/EnvironmentSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/EnvironmentInformationPropertySource.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/EnvironmentInformationPropertySourceTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/testutils/ReflectionUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/612)

Closes #604 - Providing Java and Agent version via the environment property source

---

inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/AgentManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/Test.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/EnvironmentInformationPropertySource.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/617)

Closes #610 - Send agent meta information when fetching HTTP configurations

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesAction.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/IObfuscatory.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/PatternObfuscatory.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/SelfMonitoringDelegatingObfuscatory.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/624)

Closes #623 - Enabled numeric and boolean values for span attributes

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/640)

Closes #638 - EUM server stops beacon processing when the regex beacon processor fails

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/AgentMappingsView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/EditDialog.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/635)

Closing #634 - Extend configuration server web-UI to allow duplication of existing agent mappings

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceSettingsTest.java
inspectit-ocelot-agent/src/system-test/resources/config/TraceSettingsTest.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesAction.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGeneratorTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java
inspectit-ocelot-documentation/docs/breaking-changes/1.3.md
inspectit-ocelot-documentation/docs/instrumentation/rules.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/644)

Closes #629 - Limited span attribute writing to the current method

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/RuleAutoCompleter.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/InstrumentationRuleSettings.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/InstrumentationRuleSettingsTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationRuleResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/InstrumentationConfiguration.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/InstrumentationRule.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolverTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationRuleResolverTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolverTest.java
inspectit-ocelot-documentation/docs/instrumentation/rules.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/646)

Closes #457 - Added possibility for rules to include each other

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusFooterToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/645)

Added footer toolbar to the agent status view for count statistics

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/yarn.lock
components/inspectit-ocelot-configurationserver/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/657)

Bump next from 9.1.5 to 9.3.2 to resolve security issue

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/ClassLoaderDelegationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/UserInstrumentationWithMetricsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ExecutorContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ScheduledExecutorContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ThreadStartContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ApacheHttpClientContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/GCMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/MemoryMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/ThreadMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/SelfMonitoringService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/CommonTagsManager.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImplTest.java

I went through all deprecated warnings and replaced all TagContext.put with new putLocal
there are some other deprecate warnings, too. to keep this PR ticket related it contains only requested change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/666)

Closes #233 - Replace TagContext.put with putLocal

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/logging/Log4J2LoggingRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/ZipkinExporterService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/678)

Closes #677 - Fix opencensus deprecated warnings

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/UnsavedChangesGate.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/683)

Closes #682 - Configuration UI shows incorrect warning for unsaved changes when closing it

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtilTest.java

replaced `ü` and `ß` with unicode equivalent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/676)

Closes #675 - Replace special characters with unicode

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconMetricDefinitionSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/QuantileMetricsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
inspectit-ocelot-agent/src/system-test/resources/config/QuantileMetricsTest.yml
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/MetricsSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/definition/MetricDefinitionSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/definition/ViewDefinitionSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/AsyncMetricRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/AbstractMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/ClassLoaderMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/DiskMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/GCMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/MemoryMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/ProcessorMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/ThreadMetricsRecorder.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorderTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManagerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorderTest.java

Closes #680
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/691)

Closes #680 - Added possibility to configure quantile views to the agent

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js

CLoses #603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/700)

Closes #603 - Fixed moving files with unsaved changes via drag and drop

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/selectors.js

Closes #693
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/701)

Closes #693 - Fixed sorting of default config in config UI

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/618)

Closes #320 - Select newly created configuration file added.

---

components/inspectit-ocelot-eum-server/build.gradle
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-bootstrap/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-core/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/708)

Added full exception logging to the test task of each project

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/definition/ViewDefinitionSettings.java
inspectit-ocelot-core/src/jmh/java/rocks/inspectit/ocelot/core/metrics/percentiles/WindowedDoubleQueuePerfTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileView.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/WindowedDoubleQueue.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManagerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManagerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/WindowedDoubleQueueTest.java

Closes #672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/696)

Closes #672 - Added option to limit the storage of percentile views

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js

Closes #721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/722)

Closes #721 - Fixed file sorting bug in UI

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/MetricsSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileView.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManager.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManagerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewTest.java

Closes #670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/716)

Closes #670 - Added handling of quantile views to InfluxDB exporter

---

inspectit-ocelot-documentation/docs/metrics/custom-metrics.md

Closes #692
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/719)

Closes #692 - Added documentation for percentiles

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/718)

Closes #717 - Deleting config files using keyboard

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/726)

Closes #724 - Files are not sorted lexicographically in configuration UI

---

inspectit-ocelot-demo/docker-compose-influxdb-zipkin.yml
inspectit-ocelot-demo/docker-compose-prometheus-jaeger.yml
inspectit-ocelot-demo/grafana/Dockerfile
inspectit-ocelot-demo/grafana/marketplace/influx/http.json
inspectit-ocelot-demo/grafana/marketplace/influx/selfmonitoring.json
inspectit-ocelot-demo/grafana/marketplace/influx/servicegraph.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/http.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/selfmonitoring.json
inspectit-ocelot-demo/grafana/marketplace/prometheus/servicegraph.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/http-overview-influxql.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/self-monitoring.json
inspectit-ocelot-demo/grafana/provisioning/influxdb/dashboards/service-graph-influxql.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/http-overview.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/self-monitoring.json
inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/service-graph.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/727)

Updated service dependency graph in demo

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/EditSources.js

Closes #706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/728)

Closes #706 - Fixed accidental sorting of sources in config UI

---

.github/workflows/agent_test.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/730)

Executing agent CI tests always on master

---

components/inspectit-ocelot-eum-server/build.gradle

Close #573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/754)

Closes #573 - Add boomerang Buildversion to boomerang.js

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/users/AccountController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/user/UserPermissions.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/users/AccountControllerIntTest.java

Closes #755.
In addition this PR contains a sneaky bugfix: The AgentCOnfigurationTask could fail due to an NPE in case an empty directory is encountered, because it's children in this case would be null.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/757)

Closes #755 - Added endpoint for fetching permissions

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/httpurlconnection/http-metric.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/httpurlconnection/service-graph.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/httpurlconnection/tracing.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/scopes/http/httpurlconnection.yml

Closes #743
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/749)

Closes #743 - Fixed HTTPUrlConnection instrumentation

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/model/AgentMapping.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/model/AgentMappingTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/759)

Closes #758 - Use case-insensitive check for agent-mapping assignment

---

.github/workflows/agent_test.yml
.github/workflows/configuration_ui_test.yml
.github/workflows/configurationserver_test.yml
.github/workflows/eumserver_test.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/768)

Running CI agents tests on pull requests

---

components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/InspectitConfig.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/events/EventSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/EventRecordingSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/rules/InstrumentationRuleSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationRuleResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/MethodHookConfigurationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/InstrumentationConfiguration.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/InstrumentationRule.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/model/MethodHookConfiguration.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/EventRecorder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/766)

Feature-EventExporter: Instrumenting and Resolving Events

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/rules/http/httpurlconnection/propagation.yml

Closes #769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/774)

Closes #769- Fixed HttpUrlConnection propagation

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java

Closes #750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/775)

Closes #750 - Fixed unstable TraceID-Injector tests

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/PropagationFormat.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TracingSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtil.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/PropagationFormatManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/DatadogFormat.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtilTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/793)

Closes #792, #773 - Support for Datadog and TraceContext propagation formats

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TraceIdMDCInjectionSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MDCAccess.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/JBossLogmanagerMDCAdapter.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4J1MDCAdapter.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Log4J2MDCAdapter.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/Slf4jMDCAdapter.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/adapters/JBossLogmanagerMDCAdapterTest.java
inspectit-ocelot-documentation/docs/tracing/log-correlation.md

Closes #794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/800)

Closes #794 - Added support for JBoss LogManager MDC

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfiguration.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/808)

EUM server's trace configuration conditional is correctly checked

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccessIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/817)

Closes #816 - Fixing bug in the revisionaccess' file listing

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/dialogs/EditDialog.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/823)

Closes #807 - Allow users to specify which branch an agent mapping is using as source

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/initial-states.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/LdapRoleResolveSettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/model/AgentMapping.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/PromotionController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/users/AccountController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/UserRoleConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/userdetails/CustomUserAuthoritiesMapper.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/user/UserPermissions.java
components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/users/AccountControllerIntTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/security/userdetails/CustomUserAuthoritiesMapperTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/security/userdetails/LocalUserDetailsServiceTest.java
inspectit-ocelot-documentation/docs/config-server/user-authentication.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/829)

Closes #805 - Rename the configuration server's committer role

---

inspectit-ocelot-documentation/docs/breaking-changes/1.4.md
inspectit-ocelot-documentation/docs/breaking-changes/1.5.md
inspectit-ocelot-documentation/website/sidebars.json
inspectit-ocelot-documentation/website/versioned_docs/version-1.4/breaking-changes/1.4.md
inspectit-ocelot-documentation/website/versioned_sidebars/version-1.4-sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/844)

Adding breaking changes section for version 1.4/1.5 to the documentation

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/EditSources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/841)

Closes #787 - New agent-mapping sources will be inserted at the beginning of the list

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusFooterToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/846)

Added total count to the status view

---

inspectit-ocelot-demo/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/848)

Update README.md Link

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/SimpleDiffEntry.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/WorkspaceDiff.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccessTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/PromotionControllerIntTest.java

Closes #843
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/847)

Closes #843 - Added author resolution to workspace diff

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/SecuritySettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/error/exceptions/SelfPromotionNotAllowedException.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/PromotionController.java
components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
inspectit-ocelot-documentation/docs/config-server/managing-configurations.md

Closes #837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/852)

Closes #837 - Added four eyes promotion restrictions to config-server

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionFileApproval.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionSidebar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionToolbar.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/851)

Closes #838 - Implement four-eyes principle for the web UI's file promotion view

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/util/ConfigurationFilesCacheReloadTask.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/util/ConfigurationFilesCacheReloadTaskTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/859)

Closes #857 - Warning is now only printed when an exception occurs.

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/authentication/actions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/858)

Closes #853 - Fixed permissions on token renewal

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/InspectitServerSettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/KapacitorSettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorBaseController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorEnabledController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorErrorHandler.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorNotEnabledException.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTemplateController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/exceptions/KapacitorNotEnabledException.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/exceptions/KapacitorServerException.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/KapacitorState.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Template.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/TemplateVariable.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/util/DurationUtil.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorControllerTestBase.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorEnabledControllerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTemplateControllerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/util/DurationUtilTest.java
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/templates.json
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/templates_baseline.json
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/templates_windowed_baseline.json

Closes #810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/827)

Closes #810 - Added REST-API for kapacitor templates

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTopicController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Handler.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/model/Topic.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTopicControllerTest.java
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/topic_system_handlers.json
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/topic_system_handlers_some_smtp.json
components/inspectit-ocelot-configurationserver/src/test/resources/rocks/inspectit/ocelot/rest/alert/kapacitor/topics.json

Closes #825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/863)

Closes #825 - Added API for kapacitor topics and handlers

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconTagSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/PatternAndReplacement.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/RegexReplacementBeaconProcessorTest.java
inspectit-ocelot-documentation/docs/breaking-changes/1.5.md
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

Closes #865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/866)

Closes #865 - Added multiple replacements support to EUM server

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/dialogs/RenameCopyDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/rules/tree/CreateRuleDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/CreateEditCopyHandlerDialog.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/875)

Closes #873 - fixed error message for empty entries

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/rules/editor/RulesEditorContainer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/874)

Closes #872 -  Set content to undefined when either template or rule fetching fails

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/PrometheusExporterServiceIntTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/rest/OpenTelemetryTraceControllerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/877)

Fixed EUM Prometheus Integration test

---

gradle.properties

Closes #574
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/867)

Closes #574 - Updated boomerang version

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/utils/CaseUtils.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/utils/CaseUtilTest.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/utils/CaseUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/880)

Closes #879 - Properties with non-alphabetic characters are correctly converted to kebab-case by the autocompleter 

---

components/inspectit-ocelot-configurationserver-ui/src/lib/axios-api.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/886)

Closes #885 - Increase request timeout of the configuration web UI

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/dialogs/PromotionApprovalDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/888)

Changed column order in status view and improved UI of approval dialog

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/OcelotAutocompleter.js

Closes #565
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/902)

Closes #565 - Fixed duplicate autocompletion

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/ClassLoaderDelegationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/ObjectAttachmentsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/QuantileMetricsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/correlation/log/LogCorrelationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/HttpServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/JdbcServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/ThreadStartContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4J2TraceIdAutoInjectorTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/logging/Log4JTraceIdAutoInjectorTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ApacheHttpClientContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ServletApiContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/HttpRemoteTracingTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/JigsawTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/TraceSettingsTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/service/DynamicallyActivatableService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/901)

Closes #482 - Postponed config refresh after initialization

---

.github/workflows/agent_test.yml
components/inspectit-ocelot-configurationserver/build.gradle
components/inspectit-ocelot-eum-server/build.gradle
gradle/wrapper/gradle-wrapper.properties
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-bootstrap/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-core/build.gradle
inspectit-ocelot-sdk/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/890)

Closes #882 - Updated to gradle 6.5 & lombok 1.18.12 for compatibility with JDK 13

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/WorkspaceVersion.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/versioning/VersioningController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/versioning/VersioningControllerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/906)

Closes #893 - Extend the configuration server by an endpoint for providing version information about the workspace branch

---

.github/workflows/configurationserver_test.yml
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/DirectoryController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerIntTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/DirectoryControllerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/file/FileControllerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/910)

Closes #895 - Enhance the endpoint to fetch files with the possibility to specify a version

---

components/inspectit-ocelot-configurationserver/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/917)

Fixed UI build task

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/HttpServiceOutMetricTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/926)

Increased timeout in system tests

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InternalSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/core.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/injection/ClassInjector.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/injection/ClassInjectorTest.java
inspectit-ocelot-documentation/docs/instrumentation/process.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/929)

Closes #915 - Added an option to disable recycling of old action classes

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/InfluxExporterSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterService.java
inspectit-ocelot-documentation/docs/metrics/metric-exporters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/928)

Closes #927 - Added buffering option to influx exporter

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/InfluxExporterService.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/AsyncMetricRecorder.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/CachingMetricProducer.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/PercentileView.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/PercentileViewManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/WindowedDoubleQueue.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/937)

Closes #681 - Add support for metric quantiles to the EUM server

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/correlation/log/LogCorrelationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/http/HttpOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/HttpServiceOutMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/servicegraph/ServiceInMetricTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ApacheHttpClientContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/HttpUrlConnectionContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/special/remote/ServletApiContextPropagationTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/tracing/HttpRemoteTracingTest.java
inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/utils/TestUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/941)

Increased timeouts from 10s to 30s for system tests

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/940)

Improved documentation for contribution process

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java

Closes #942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/944)

Closes #942 - Prevented LiveBeansView within inspectIT from starting

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ScopeAutoCompleter.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InstrumentationSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettings.java
inspectit-ocelot-config/src/test/java/rocks/inspectit/ocelot/config/model/instrumentation/scope/InstrumentationScopeSettingsTest.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationScopeResolver.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationScopeResolverTest.java
inspectit-ocelot-documentation/docs/instrumentation/scopes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/943)

Closes #525 - Allow scopes to exclude certain methods / classes

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/947)

Closes #946 Extend the "illegal tag value" error message with the specified value

---

inspectit-ocelot-core/src/main/resources/inspectit-logback.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/949)

fix logDir Variable in logback.xml

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/filters/AccessLogFilter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/965)

Closes #964 - Change the log level for failed authentications

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/TagUtils.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/utils/TagUtilsTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/972)

Closes #971 - Extend the "illegal tag value" error message, to specify which tag is concerned.

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/DiskMetricsRecorderConfigTest.java

closes #978
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/979)

Closes #978 - SpringTestBase attaches multiple log appenders for log message verification

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/BeaconECSSerializer.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconExporterSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconHttpExporterSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumServerConfiguration.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporter.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/rest/BeaconController.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactoryTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/rest/BeaconControllerTest.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml
inspectit-ocelot-documentation/docs/breaking-changes/1.7.md
inspectit-ocelot-documentation/docs/breaking-changes/1.8.md
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
inspectit-ocelot-documentation/docs/instrumentation/rules.md
inspectit-ocelot-documentation/website/sidebars.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/984)

Closes #977 - EUM server can export received beacons via http

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconHttpExporterSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactoryTest.java
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/987)

Closes #985 - Extend EUM server HTTP beacon exporter to be able to use authentications

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporter.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/rest/BeaconController.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java

closes #988
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/989)

Closes #988 - EUM server is not starting when beacon export configuration is missing

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorder.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/ResourceTimingSettings.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/recorder/ResourceTimingBeaconRecorderTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/metrics/definition/ViewDefinitionSettings.java

Closes #968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/992)

Closes #968 - Extend the resource-timing collection in the EUM server to be able to specify tags

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/AsyncMetricRecorder.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/TimeWindowViewManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/percentiles/WindowedDoubleQueue.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/percentiles/WindowedDoubleQueue.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/percentiles/PercentileViewManagerTest.java

Closes #990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/991)

Closes #990 - IllegalArgumentException: The provided timestamp is older than the most recent timestamp present in the queueDec

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/EditSourceComponents/SourceTree.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/995)

Closes #993 - Activated filter option on Tree in SourceTree

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporter.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1002)

Closes #1001 - ConditionalOnProperty now refers to correct place in the configuration

---

inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1007)

Closes #1006 - Added important-box with information about how to disable self-monitoring.

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml

Closes #1015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1016)

Closes #1015 - Wrong characters in the agent's service name when fetching HTTP endpoints

---

inspectit-ocelot-documentation/docs/enduser-monitoring/enduser-monitoring-server.md
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
inspectit-ocelot-documentation/docs/enduser-monitoring/install-eum-agent.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1013)

Closes #1012 - Add Code-Snippets to exporter documentation of EUM-Server

---

.github/workflows/eumserver_test.yml
components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/JaegerExporterIntTest.java

closes #1014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1017)

Closes #1014 - Fix GRPC version of the EUM server

---

inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
inspectit-ocelot-documentation/docs/enduser-monitoring/install-eum-agent.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1018)

Minor documentation fixes

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/gradle.properties
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/AppStartupRunner.java
gradle.properties

closes #934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1020)

Closes #934 - Update Boomerangjs to 1.720.0

---

components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/service/RestartService.java
components/inspectit-ocelot-eum-server/src/main/resources/static/package.json
components/inspectit-ocelot-eum-server/src/main/resources/static/yarn.lock
components/inspectit-ocelot-eum-server/src/main/resources/templates/configuration.html

This pull request fixes two bugs of the ui of the eum server:
- Apply now also works with Mac & Linux
- Added a missing dependency which caused the endpoint to throw exceptions
- Added toasts for feedback on button clicks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1036)

Bugfixes and improvements for EUM UI

---

components/inspectit-ocelot-configurationserver-ui/src/components/login/LoginCard.js

closes #1027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1031)

Closes #1027 - Set focus on username input on login screen

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/AsyncClassTransformer.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/InstrumentationTriggerer.java

closes #512
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1038)

Closes #512 - Improved error log when classes could not been loaded

---

inspectit-ocelot-agent/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-sdk/build.gradle

I want to make the agent available via https://jitpack.io/.
In my opinion, this will be useful for others. Could you please merge this?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1039)

Publish agent, test with https://jitpack.io/

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/events/RegisteredTagsEvent.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManager.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManager.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManagerTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/MeasuresAndViewsManagerTest.java

closes #1032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1041)

Closes #1032 - EUM server tag context optimization

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1053)

Fix CannotStubVoidMethodWithReturnValue

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/StaticAppender.java

closes #1057
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1058)

Closes #1057 - Replace Mock Appender in SpringTestBase

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/GCMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/MemoryMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/ThreadMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/SelfMonitoringService.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/CommonTagsManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/tags/TagUtils.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/tags/TagUtilsTest.java

closes #1048
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1052)

Closes #1048 - Extend the 'illegal tag value' error message, to specify which tag is concerned

---

components/inspectit-ocelot-eum-server/src/main/java/io/opentelemetry/sdk/trace/OcelotSpanUtils.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/ClientHeaderBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumTraceExportersSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/tracing/opentelemtry/OpenTelemetryProtoConverter.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/RequestUtils.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/rest/TraceControllerIntTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/tracing/opentelemtry/OpenTelemetryProtoConverterTest.java
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1062)

Extending EUM server to enrich received spans with additional tags

---

components/inspectit-ocelot-configurationserver-ui/.storybook/main.js
components/inspectit-ocelot-configurationserver-ui/.storybook/preview.js
components/inspectit-ocelot-configurationserver-ui/README.md
components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/src/components/common/dialogs/DeleteDialog.stories.js
components/inspectit-ocelot-configurationserver-ui/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1089)

Adding Storybook to the configuration UI project

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js

closes #1071
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1097)

Closes #1071 - Toggles of UI now change the respective values in the underlying file

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js

closes #1072
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1098)

Closes #1072 - Delete button of UI now deletes the respective scope.

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/CBTableNode.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.stories.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserUtilities.js

closes #1077
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1100)

Closes #1077 - Implement a dialog for browsing classes and methods of an agent

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditorFooter.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditorFooter.stories.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/MethodMatcher.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/TypeMatcher.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/TypeMatcher.stories.js
components/inspectit-ocelot-configurationserver-ui/yarn.lock

closes #1076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1099)

Closes #1076 - Extend the graphical configuration view in order to support the creation of new scopes

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/CBTableNode.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserUtilities.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js

closes #1078
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1101)

Closes #1078 - Extend the class browser dialog to use real data from the configuration server

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/ScopeMethodDisplay.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/ScopeMethodDisplay.stories.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/MethodMatcher.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.stories.js

closes #1080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1102)

Closes #1080 - Implement functionality to edit scopes via the graphical config view

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/CBTableNode.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserUtilities.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/impl/ListClassesHandler.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentcommunication/handlers/impl/PingCommandHandler.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/command/AgentCommandController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentcommunication/handlers/impl/PingCommandHandlerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleterTest.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/Command.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/impl/ListClassesCommand.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/response/CommandResponse.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/commons/models/command/response/impl/ListClassesResponse.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/handler/impl/ListClassesCommandExecutor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/NewClassDiscoveryService.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/handler/impl/ListClassesCommandExecutorTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1103)

Implementing agent command for listing loaded classes

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js

closes #1079
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1104)

Closes #1079 - Extend the scope wizard so that the class browser can be used

---

inspectit-ocelot-core/build.gradle

closes #1050
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1106)

Closes #1050 - Upgrade ByteBuddy to the latest version

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/AsyncClassTransformer.java

closes #1081
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1110)

Closes #1081 - Improve logging of the AsyncClassTransformer

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/MethodMatcher.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js

closes #1107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1111)

Closes #1107 - ScopeWizard is not correctly handling the method argument matcher

---

inspectit-ocelot-core/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1116)

Upgrading ByteBuddy to 1.11.5

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/class-browser/ClassBrowserUtilities.js

closes #1109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1118)

Closes #1109 - The agent list of the class browser should be sorted and filterable

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/CommandHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1119)

Prevent agent command handler from continuously sending requests in live mode

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1120)

Visual editor shows existing properties in case configuration is empty

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js
components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/reducers.js

closes #1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1126)

Closes #1046 - Editor of the web UI deletes its content when switching between files

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/dialogs/WarningDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/common/dialogs/WarningDialog.stories.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/promotion/PromotionView.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/PromotionResult.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/PromotionController.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/configuration/PromotionControllerIntTest.java

closes #1144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1146)

Closes #1144 - Show a warning in case a configuration promotion is failing due to an out-of-sync branch

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/BeanConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/RemoteConfigurationsSettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/config/model/SecuritySettings.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/filters/WebhookAccessFilter.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/hook/WebhookController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/security/config/SecurityConfiguration.java
components/inspectit-ocelot-configurationserver/src/main/resources/application.yml
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/hook/WebhookControllerTest.java

closes #1139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1147)

Closes #1139 - Implement an endpoint for configuration synchronization using web-hooks

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/ClientHeaderBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CompositeBeaconProcessorTest.java
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

closes #1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1122)

Closes #1121 - ﻿﻿Add selfmonitoring metric for the beacon processors

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1151)

Fix nullPointer Exception in file type resolver

---

components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingWorkingDirectoryAccessorTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/StackTraceTest.java

Fixes https://github.com/inspectIT/inspectit-ocelot/issues/1153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1154)

Closes #1153 - Fix minor testcase issues

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleter.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/util/ConfigurationQueryHelper.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/AsyncClassTransformer.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/SampledTrace.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/matcher/SpecialElementMatchers.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1158)

Closes #1157 - Check Collection emptiness with isEmpty()

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/configuration/PromotionController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/file/FileController.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/Beacon.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumServerConfiguration.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/ResourceTimingSettings.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/privacy/obfuscation/impl/NoopObfuscatory.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1166)

Closes #1165 - Remove unused imports

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/file/ConfigurationDirectoriesPoller.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPoller.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/InspectitContextImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/HookManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodReflectionInformation.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1162)

Closes #1161 - Remove shadow fields

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1168)

Closes #1167 - Add Iterator.next() "NoSuchElementException"

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingManager.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1172)

Closes #1171 - Fix asymmetric get/set synchronized

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileInfoVisitor.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/FileInfoVisitorTest.java

closes #1176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1179)

Closes #1176 - Potential NPE in the Configuration Server's FileInfoVisitor if no element with the "type" key exist

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/rest/TraceController.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

closes #955
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1182)

Closes #955 - Add selfmonitoring metric for the received traces and span sizes

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/AsyncClassTransformer.java

closes #1195
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1196)

Closes #1195 - Change the agent's transformation approach to decorateinstead of redefine

---

inspectit-ocelot-core/build.gradle
inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1208)

Upgrading ByteBuddy to the latest version

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/workingdirectory/CachingWorkingDirectoryAccessor.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTaskController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTemplateController.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/alert/kapacitor/KapacitorTopicController.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/correlation/log/MdcAccessManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorder.java

Fixes https://github.com/inspectIT/inspectit-ocelot/issues/1155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1156)

Closes #1155 - Null pointers should not be dereferenced

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/model/SimpleDiffEntry.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1164)

Closes (#1163) Replace Stream.peek with map

---

inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentMain.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/validation/PropertyPathHelper.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/handler/impl/ListClassesCommandExecutor.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/Invocation.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/autotracing/InvocationResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationScopeResolver.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextManager.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/MethodHookGenerator.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/MetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/jmx/JmxMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/system/GCMetricsRecorder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/plugins/PluginLoader.java

Fix https://github.com/inspectIT/inspectit-ocelot/issues/1169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1170)

Closes #1169 - Refactor Boolean logic

---

.gitignore
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java

closes #1214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1215)

Closes #1214 - Configuration Server fails calculating the common commit ancestor in case merge commits happened

---

.gitignore
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/InstrumentationSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/core.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolver.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/InstrumentationConfigurationResolverTest.java
inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
inspectit-ocelot-documentation/docs/instrumentation/instrumentation.md
inspectit-ocelot-documentation/docs/instrumentation/process.md

closes #1221
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1222)

Closes #1221 - Implement flag for disabling the instrumentation

---

components/inspectit-ocelot-configurationserver/docker/Dockerfile
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleterTest.java

closes #1199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1225)

Closes #1199 - Switch base image for the docker image of the configuration server

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1229)

Closes #1228 -  Omit unnecessary merge commit when restarting the config server and using one remote repo for push and pull

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/RemoteConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
inspectit-ocelot-documentation/docs/config-server/configuration-staging.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1210)

Closes #1209 - Live branch is synchronized with remote target branch to allow for pushing without force

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/logic.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1235)

Add isTrueOrNotNull action to common actions

---

gradle.properties
inspectit-ocelot-core/build.gradle

Closes #1245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1247)

Closes #1245 - Upgrade OpenCensus to the latest java release version (v0.28.3) 

---

components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/agentcommunication/handlers/impl/PingCommandHandlerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/RuleAutoCompleterTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/ExternalChangeDetectorTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/mappings/AgentMappingControllerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/security/jwt/JwtTokenManagerTest.java
components/inspectit-ocelot-eum-server/build.gradle
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/BeaconMetricManagerTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/metrics/SelfMonitoringMetricManagerTest.java
gradle.properties
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/AgentCommandServiceTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpConfigurationPollerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/PropagationMetaDataResolverTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/config/model/propagation/CompositePropagationMetaDataTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/ContinueOrStartSpanActionTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/SetSpanStatusActionTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/hook/actions/span/WriteSpanAttributesTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/special/ExecutorContextPropagationSensorTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/special/ScheduledExecutorContextPropagationSensorTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManagerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/LogMetricsAppenderTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/LogMetricsIntTest.java

Closes #1243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1244)

Closes #1243 - Upgrade mockito-core:2.24.4 to mockito-inline:4.1.0

---

inspectit-ocelot-agent/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1253)

Upgrade Log4J dependency for system tests

---

components/inspectit-ocelot-eum-server/gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1258)

Bump Boomerang version of EUM server

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/rest/versioning/VersioningControllerIntTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1256)

Closes #1238 - Agent mappings are pushed to remote git repository on config server initialization

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/versioning/VersioningManager.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/versioning/VersioningManagerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1255)

Closes #1237 - Always hard-reset on initialization when pulling from and pushing to the same branch

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/service/DynamicallyActivatableService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1261)

Catching exception while checking configuration dependencies

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManager.java

closes #1051
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1265)

Closes #1051 - Change log levels used by the metrics manager

---

THIRD-PARTY-LICENSES.txt
build.gradle
gradle.properties
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-core/build.gradle

closes #1266
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1268)

Closes #1266 - Upgrading logback-classic version

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccess.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/accessor/git/RevisionAccessTest.java

closes #1272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1273)

Closes #1272 - Fix RevisionAccess slash resolving

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/file/FileManagerTest.java

closes #1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1275)

Closes #1234 - Invalidating working directory cache when commiting new files

---

inspectit-ocelot-documentation/docs/getting-started/docker-examples.md

closes #1264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1305)

Closes #1264 – Added a disclaimer for the Docker Demo

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleter.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/autocomplete/autocompleterimpl/ModelAutoCompleterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1339)

Closes #1319 - Add filter for inspectit.env path in autocompletion

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/DocumentationView.js
components/inspectit-ocelot-configurationserver-ui/src/hooks/use-fetch-data.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1340)

feat(ui): reload documentation when configuration files are changed

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/ConfigDocumentation.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/DocumentationView.js
components/inspectit-ocelot-configurationserver-ui/src/hooks/use-debounce.js

Refs: #1288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1341)

feat(ui): ability to filter configuration docs

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/BeaconHttpExporterSettings.java
components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporter.java
components/inspectit-ocelot-eum-server/src/main/resources/application.yml
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1344)

fix(EUM-server): update Beacon Exporter enabled

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/exporters/beacon/ExportWorkerFactory.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterAnnotationsTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/beacon/BeaconHttpExporterTest.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/exporters/configuration/TraceExportersConfigurationTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1345)

fix(EUM-Server): Addition to Beacon exporter fix

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/DocumentationView.js

closes #1352
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1353)

feat(config-ui): [#1352] filterable list of agent mappings in configuration docs

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/InspectitConfigConversionService.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/conversion/StringToExporterEnabledStateConverter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1357)

Closes #1356 - fix(config) - Add converter for String to ExporterEnabledState

---

.github/workflows/agent_test.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/metrics/MeasuresAndViewsManagerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1368)

feat(ci): including Java 17 into the ci process

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/ConfigDocumentation.js

Closes #1378
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1379)

Closes #1378 - Preserve whitespaces in Configuration Docs

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CountryCodeBeaconProcessor.java
components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/beacon/processor/CountryCodeBeaconProcessorTest.java

closes #1381
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1382)

Closes #1381 - Respecting forwarded-for header when recording beacon metrics

---

inspectit-ocelot-documentation/website/siteConfig.js

Closes #1387
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1388)

Closes #1387 - Migrate Algolia DocSearch

---

inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1399)

Fixing missing breaking changes paragraphs

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/yarn.lock

closes #1400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1401)

Closes #1400 - Upgrading axios to the latest version

---

components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/CountryCodeBeaconProcessor.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1402)

Remove redundant lookup of forward headers

---

inspectit-ocelot-documentation/docs/getting-started/docker-examples.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1412)

Replace Wavefront instructions with collection of additional scenarios in Docs

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/InspectitEnvironment.java

Closes #1418
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1424)

Improve exception message for invalid fallback config

---

components/inspectit-ocelot-configdocsgenerator/src/main/java/inspectit/ocelot/configdocsgenerator/ConfigDocsGenerator.java
components/inspectit-ocelot-configdocsgenerator/src/test/java/inspectit/ocelot/configdocsgenerator/ConfigDocsGeneratorTest.java
components/inspectit-ocelot-configdocsgenerator/src/test/resources/ConfigDocGeneratorTest/actionWithDocInYaml.yml
components/inspectit-ocelot-configdocsgenerator/src/test/resources/ConfigDocGeneratorTest/all.yml
components/inspectit-ocelot-configdocsgenerator/src/test/resources/ConfigDocGeneratorTest/multipleActions.yml

Closes #1416
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1423)

Add descriptions for special input parameters in Configuration Docs

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/file/FileManager.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1445)

Closes #1234 - Invalidating workspace after pull from remote-workspace

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/http/httpurlconnection.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1448)

Use correct request method in span names for httpconnection

---

inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/metrics/MetricsExportersSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/exporters/trace/TraceExportersSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/exporters.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java
inspectit-ocelot-documentation/docs/tracing/trace-exporters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1443)

Closes #1442 - Add Service Name Tag for Metric/Trace Exporters

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterService.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceIntTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/JaegerExporterServiceTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1449)

Closes #1447 - Jaeger Span Exporter is restarted on every configuration change

---

.circleci/config.yml
components/inspectit-ocelot-eum-server/gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1451)

Fix Prometheus version of EUM-Server

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/yaml-editor/InspectitOcelotHighlightRules.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/alerting/topics/editor/HandlerEditor.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1456)

Fix inefficient regular expressions

---

inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/DynamicSampler.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/DynamicSamplerTest.java
inspectit-ocelot-documentation/docs/instrumentation/rules.md
inspectit-ocelot-documentation/docs/tracing/tracing.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1474)

Using a parent based sampling decision as default sampler

---

inspectit-ocelot-documentation/docs/tracing/trace-exporters.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1483)

Fix property name in trace-exporters documentation

---

components/inspectit-ocelot-configurationserver-ui/src/redux/ducks/configuration/actions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1482)

Closes #1480 - Directories are loaded correctly when adding a new agent mapping

---

components/inspectit-ocelot-configurationserver-ui/src/components/layout/Menubar.js

closes #975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1492)

closes #975 Add a button to the Config UI that links to the documentation

---

.github/workflows/agent_test.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1497)

Add more ignored paths for agent tests

---

inspectit-ocelot-documentation/website/pages/en/versions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1503)

Closes #1438: Fix release notes links in documentation

---

components/inspectit-ocelot-configurationserver-ui/package.json
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/dialogs/CreateDialog.js
components/inspectit-ocelot-configurationserver-ui/yarn.lock

Closes #914 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1485)

Closes #914: [Feature] Expand configuration file tree when jumping to a file

---

inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
inspectit-ocelot-documentation/website/versioned_docs/version-1.16.0/breaking-changes/breaking-changes.md
inspectit-ocelot-documentation/website/versioned_docs/version-2.0.0/breaking-changes/breaking-changes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1511)

Fix links in breaking-changes

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/ExporterServiceIntegrationTestBase.java

Closes #1508
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1509)

Closes #1508: Use specific otel-collector image instead of latest

---

.github/workflows/agent_test.yml
build.gradle
components/inspectit-ocelot-configdocsgenerator/build.gradle
components/inspectit-ocelot-configurationserver/build.gradle
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-bootstrap/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/selfmonitoring/AgentHealthSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/self-monitoring.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/com/mindprod/jarcheck/JarCheck.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManager.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/selfmonitoring/AgentHealthManagerTest.java
inspectit-ocelot-sdk/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1521)

Fix/agenthealthmanager 2.1.1

---

.github/workflows/configurationserver_test.yml
components/inspectit-ocelot-configurationserver/build.gradle

Try to fix compatibility issues with dependencies, yarn, and node
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1541)

Fix configurationserver ui dependencies/yarn/node mismatch

---

THIRD-PARTY-LICENSES.txt
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializerIntTest.java
inspectit-ocelot-core/src/test/resources/test-logback-with-logstash.xml

Closes #1546
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1550)

Closes #1546: [Bug] - Agent throws exception if logback config contains net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder

---

inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1568)

Documents Security configuration for EUM-Server

---

.github/workflows/release.yml
README.md

Delete Tests in release Github Action + Added Config UI Tests status badge to README.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1586)

Delete Tests in release Github Action + Added Config UI Tests status badge to README

---

gradle.properties
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/com/mindprod/jarcheck/JarCheck.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1590)

New spring release

---

.github/workflows/configurationserver_test.yml
gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1591)

Uses correct SnakeYaml version

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/MappingsTable.js

Closes #1592
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1593)

Fix styling in AgentMappingTable Sourc Col

---

.github/workflows/release.yml

Closes #1595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1596)

Update changelog generation to fix deprecated warning

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1604)

Allows release action to push to master

---

.github/workflows/release.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1605)

Specifies environment for action step

---

.github/workflows/release.yml
components/inspectit-ocelot-configurationserver-ui/next.config.js

Closes #1607 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1608)

Fix version display in login page of config ui

---

THIRD-PARTY-LICENSES.txt
gradle.properties
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/command/AgentCommandSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/HttpConfigSettings.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/config/RetrySettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/config-sources.yml
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/CommandHandler.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/HttpCommandFetcher.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/utils/RetryUtils.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/CommandHandlerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java
inspectit-ocelot-documentation/docs/configuration/agent-command-configuration.md
inspectit-ocelot-documentation/docs/configuration/external-configuration-sources.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1609)

Agent accesses configuration server using retries with exponential backoff

---

gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1610)

Updates Spring Boot to 2.7.12

---

.github/workflows/release.yml
gradle/libs.versions.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1634)

fix release workflow

---

components/inspectit-ocelot-configurationserver-ui/src/components/common/dialogs/ConvertDialog.js
components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/MethodConfigurationEditor.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/ConfigurationView.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileTree.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/mappings/editComponents/KeyValueEditor.js

Fix agent-mapping-editor, method-configuration-editor as well as minor bugs in the config-server-ui
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1636)

Fix config server

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/status/StatusTable.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentconfiguration/AgentConfigurationManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/agentstatus/AgentStatusManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/rest/agent/AgentController.java
components/inspectit-ocelot-configurationserver/src/main/resources/logback.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1645)

Extend logging

---

components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializer.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1649)

Reload cached mappings after workspace changes

---

inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/InfluxExporterServiceIntTest.java

There was a problem with the download of InfluxDB, when using JDK 8 from IBM.  Should be fixed with testcontainer setup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inspectIT/inspectit-ocelot/1673)

fix: Use Testcontainer for InfluxExporterIntTest 

---

components/inspectit-ocelot-configurationserver/docker/Dockerfile

Closes https://github.com/inspectIT/inspectit-ocelot/issues/1025

update configurationserver base image

---

components/inspectit-ocelot-configurationserver-ui/src/components/editor/method-configuration-editor/constants.js
components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/FileToolbar.js
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingManager.java
components/inspectit-ocelot-configurationserver/src/main/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializer.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/IntegrationTestBase.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingManagerTest.java
components/inspectit-ocelot-configurationserver/src/test/java/rocks/inspectit/ocelot/mappings/AgentMappingSerializerTest.java

Closes https://github.com/inspectIT/inspectit-ocelot/issues/1530 
Closes https://github.com/inspectIT/inspectit-ocelot/issues/1408 
Closes https://github.com/inspectIT/inspectit-ocelot/issues/1689

improve configurationserver

---

components/inspectit-ocelot-configdocsgenerator/build.gradle
components/inspectit-ocelot-configurationserver/build.gradle
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-bootstrap/build.gradle
inspectit-ocelot-config/build.gradle
inspectit-ocelot-core/build.gradle
inspectit-ocelot-sdk/build.gradle

Closes https://github.com/inspectIT/inspectit-ocelot/issues/1616

Closes #1616 - fix maven-publish

---

README.md
THIRD-PARTY-LICENSES.txt
components/inspectit-ocelot-configurationserver/build.gradle
gradle/libs.versions.toml
inspectit-ocelot-agent/build.gradle
inspectit-ocelot-core/build.gradle
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/CommandHandler.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/HttpCommandFetcher.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/http/CommandHttpClientHolder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpClientHolder.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceState.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/CommandHandlerTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/command/http/CommandHttpClientHolderTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpClientHolderTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/config/propertysources/http/HttpPropertySourceStateTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/BrowserPropagationHttpExporterServiceIntTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/exporter/PrometheusExporterServiceIntTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImplIntTest.java

Closes https://github.com/inspectIT/inspectit-ocelot/issues/1749

Closes #1749 - Update HTTP client

---

components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/scope-wizard/ScopeWizardDialog.js

Closes #1366 - Fix apply button

---

inspectit-ocelot-agent/src/system-test/java/rocks/inspectit/ocelot/instrumentation/InspectitAgentInfoTest.java
inspectit-ocelot-agent/src/system-test/resources/config/InspectitAgentInfoTest.yml
inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/Instances.java
inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/exposed/InspectitAgentInfo.java
inspectit-ocelot-bootstrap/src/main/java/rocks/inspectit/ocelot/bootstrap/instrumentation/noop/NoopInspectitAgentInfo.java
inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/instrumentation/actions/GenericActionSettings.java
inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/_shared/agent.yml
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/AgentInfoImpl.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/config/spring/BootstrapInitializerConfiguration.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/hook/VariableAccessorFactory.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/AgentInfoImplTest.java
inspectit-ocelot-documentation/docs/instrumentation/actions.md

Closes #1316 - Add agent information for actions

---

inspectit-ocelot-documentation/docs/instrumentation/data-propagation.md

Closes #1808 - Add overview for global storages

---

inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
inspectit-ocelot-documentation/docs/tracing/tracing.md

Closes #1440 - Fix naming for inspectit.tracing.use64-bit-trace-ids

---

inspectit-ocelot-agent/src/main/java/rocks/inspectit/ocelot/agent/AgentJars.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/B3Format.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/BaggagePropagation.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/ContextPropagation.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/DatadogFormat.java
inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/TraceContextPropagation.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/B3FormatTest.java
inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/instrumentation/context/propagation/ContextPropagationTest.java

Closes #1249 - Support case-insensitive headers for context-propagation

---

.github/workflows/agent_security_check.yml
.github/workflows/agent_test.yml
.github/workflows/configdocsgenerator_test.yml
.github/workflows/configschemagenerator.yml
.github/workflows/configuration_ui_test.yml
.github/workflows/configurationserver_security_check.yml
.github/workflows/configurationserver_test.yml
.github/workflows/docs_deployment_test.yml
.github/workflows/release.yml
.github/workflows/snyk_test_sarif.yml
.github/workflows/third_party_license_update.yml
build.gradle
components/inspectit-ocelot-configdocsgenerator/build.gradle
components/inspectit-ocelot-configschemagenerator/build.gradle
components/inspectit-ocelot-configurationserver/build.gradle
components/inspectit-ocelot-configurationserver/docker/Dockerfile
inspectit-ocelot-documentation/docs/breaking-changes/breaking-changes.md
settings.gradle

Closes #1813 - Configuration server requires Java 21
